using AuthLib.Interfaces.Services;
using AuthLib.Models;
using AuthLib.Options;
using AuthLib.Services.IdGenerators;
using AuthLib.Services.Stores;

namespace AuthLib.Services
{
    internal sealed class RoleSeederService<TKey, TUser, TRole>(RoleStore<TKey, TUser, TRole> roleStore) : IRoleSeederService
        where TKey : IEquatable<TKey>
        where TUser : AuthUser<TKey, TRole>
        where TRole : AuthRole<TKey>, new()
    {
        private readonly RoleStore<TKey, TUser, TRole> _roleStore = roleStore;

        public async Task SeedRolesAsync(IReadOnlyList<Role> roles, CancellationToken ct)
        {
            if (roles.Count(r => r.IsDefault) > 1)
            {
                throw new Exception("Only one default role allowed");
            }

            List<TRole> existingRoles = await _roleStore.GetAllAsync(ct);

            Dictionary<string, TRole> existingRolesDict = existingRoles.ToDictionary(r => r.Name, StringComparer.InvariantCultureIgnoreCase);

            foreach (var role in roles)
            {
                if (role.IsDefault)
                {
                    CreateDefaultRole(role.Name, existingRolesDict, ct);

                }
                else
                {
                    CreateRole(role.Name, existingRolesDict, ct);
                }
            }

            DeactivateMissingRoles(roles, existingRoles);

            await _roleStore.Context.SaveChangesAsync(ct);
        }


        private void CreateRole(string roleName, Dictionary<string, TRole> existingRolesDict, CancellationToken ct)
        {
            if (existingRolesDict.ContainsKey(roleName))
            {
                return;
            }

            _roleStore.Add(new TRole
            {
                Id = IdGenerator<TKey>.IsAutoGenerated() ? default! : IdGenerator<TKey>.GenerateId(),
                Name = roleName
            });
        }

        private void CreateDefaultRole(string roleName, Dictionary<string, TRole> existingRolesDict, CancellationToken ct)
        {
            if (existingRolesDict.TryGetValue(roleName, out var existingRole))
            {
                if (existingRole.IsDefault)
                    return;

                var previousDefaultRole = existingRolesDict
                    .FirstOrDefault(r => r.Value.IsDefault).Value;

                if (previousDefaultRole != null)
                {
                    previousDefaultRole.IsDefault = false;
                }

                existingRole.IsDefault = true;
                return;
            }

            TRole role = new TRole
            {
                Id = IdGenerator<TKey>.IsAutoGenerated() ? default! : IdGenerator<TKey>.GenerateId(),
                Name = roleName,
                IsDefault = true
            };

            existingRolesDict.Add(roleName, role);

            _roleStore.Add(role);
        }

        private static void DeactivateMissingRoles(
            IReadOnlyList<Role> roles,
            IReadOnlyList<TRole> existingRoles)
        {
            foreach (var existingRole in existingRoles)
            {
                bool shouldBeActive = roles.Any(r => r.Name.Equals(existingRole.Name, StringComparison.InvariantCultureIgnoreCase));
                if (existingRole.IsActive != shouldBeActive)
                {
                    existingRole.IsActive = shouldBeActive;
                }
            }
        }
    }
}
