namespace AuthLib.Services.IdGenerators
{
    internal static class IdGenerator<TKey> where TKey : IEquatable<TKey>
    {
        public static TKey GenerateId()
        {
            var type = typeof(TKey);

            if (type == typeof(Guid))
            {
                return (TKey)(object)Guid.NewGuid();
            }
            else if (type == typeof(string))
            {
                return (TKey)(object)Guid.NewGuid().ToString();
            }
            else if (type == typeof(int))
            {
                return default!;
            }
            else if (type == typeof(long))
            {
                return default!;
            }
            else
            {
                throw new NotSupportedException($"ID generation for type {type.Name} is not supported. " +
                    $"Supported types are: Guid, string, int, long.");
            }
        }

        public static bool IsAutoGenerated()
        {
            var type = typeof(TKey);
            return type == typeof(int) || type == typeof(long);
        }
    }
}
